### ISSUE TITLE
To which section should Awesome React Native Meteor be submitted?

### ISSUE THREAD

**Issue by yogiben** [jondot/awesome-react-native#123]
This is a list of resources. Which section is most appropriate?

https://github.com/meteor-factory/awesome-react-native-meteor

**Comment by jondot** [comment]
I believe we don't have that category yet. What do you think of "Platforms" or "Frameworks"?

**Comment by yogiben** [comment]
I went for Frameworks as there as already a header with 'Platforms' in it.

https://github.com/jondot/awesome-react-native/pull/124
