### ISSUE TITLE
New cross platform navigation bar componenent

### ISSUE THREAD

**Issue by jineshshah36** [jondot/awesome-react-native#136]
I wrote a library called [react-native-nav](https://github.com/jineshshah36/react-native-nav) which is loosely based on [react-native-navbar](https://github.com/react-native-fellowship/react-native-navbar) but is significantly more customizable, works on iOS and Android, and works well with flux and redux. Please check it out and add it if you think it is good!

**Comment by jondot** [comment]
Hi, can you please make a pull request?
Thanks!
