### ISSUE TITLE
Awesome list

### ISSUE THREAD

**Issue by DanielMSchmidt** [jondot/awesome-react-native#178]
Hi,

Just curious if there would be any interest in joining [sindresorhus awesome list](https://github.com/sindresorhus/awesome)? It may add some visibility to this awesome project. I would do a PR, if that is of interest for you.

Have a nice day!

**Comment by jondot** [comment]
Feel free!

On Monday, 23 May 2016, Daniel Schmidt <notifications@github.com> wrote:

> Hi,
>
> Just curious if there would be any interest in joining sindresorhus
> awesome list <https://github.com/sindresorhus/awesome>? It may add some
> visibility to this awesome project. I would do a PR, if that is of interest
> for you.
>
> Have a nice day!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jondot/awesome-react-native/issues/178>
>


-- 
--
Dotan, @jondot <http://twitter.com/jondot>
