### ISSUE TITLE
react-native-animatable seems missing

### ISSUE THREAD

**Issue by ChrisOHu** [jondot/awesome-react-native#228]
Hi guys,

Great work here : )

Came across this repo (https://github.com/oblador/react-native-animatable), and it seems ARN hadn't added it yet.

Best,
Chris

**Comment by jondot** [comment]
Hi @ChrisOHu feel free to submit a pull request! :)

**Comment by ChrisOHu** [comment]
Hi guys, PR submitted ☀️
