### ISSUE TITLE
Misses a license and contributing guidelines

### ISSUE THREAD

**Issue by arthurvr** [jondot/awesome-react-native#26]
* This repo misses a license.
* You could use this one for inspiration: https://github.com/sindresorhus/awesome/blob/master/contributing.md

Ref https://github.com/sindresorhus/awesome/issues/207

**Comment by jhabdas** [comment]
This repo does not currently use the awesome badge proposed in #33. @arthurvr do you have time to create a PR for this? Otherwise I don't see any issues as it's just free-floating information - use it!

**Comment by arthurvr** [comment]
> Otherwise I don't see any issues as this is just free-floating information - use it!

That's where this is about. Not having a license limits the use cases. See: https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license.

**Comment by jhabdas** [comment]
This is an open repo accepting PRs. It's a list of info. It's crawlable by
search bots. Anyone can use it, with the exception of those creating
derivative works according to the above doc. One could say Search Engines
are also creating derivative works. And, if so, how can they do that
currently?

**Comment by jondot** [comment]
For the topic of licenses or badges, I want to keep it simple. I don't see any reason for bureaucracy and limits, it's just a bunch of links, I agree with @jhabdas so do what ever you want with the content. Thanks for taking the time to bring this to my attention!
