### ISSUE TITLE
Move to react-native-community?

### ISSUE THREAD

**Issue by satya164** [jondot/awesome-react-native#291]
We've a community organisation over at https://github.com/react-native-community

It would be really awesome if we can have this repo there.

**Comment by jondot** [comment]
Hi Satya!
I'm embarrassed to say I've just got to know this organization, and it looks like a much needed effort, kudos!

I feel this list wouldn't be a good fit there, but now that I know about it, I think I have a few things to offer that would be great there, for example, https://github.com/react-native-templates which we started at the React Native Israel Facebook Hackathon, [and won](https://twitter.com/jondot/status/746047657395761152). What do you think?

**Comment by satya164** [comment]
Hey. Sorry, totally forgot about the issue due to work and stuff.

I still think this list is a good fit there. But upto you :)

Yeah, we can do that too. What do you guys think @knowbody @grabbou @Kureev?

**Comment by jondot** [comment]
That's OK, seems like I'm swamped too :)
The idea for the templates, is to have a bit more meaningful starting point after an `init`. There were plenty of dilemmas during that hackathon, like where is the line crossing between having it be an adopt-the-world boilerplate, a nothing-useful starter, or something with "Just Enough" to be valuable later on, and also if we took on external deps - how long will it get until templates break.

Eventually, we thought to take the spirit of the original generated app, and do as minimal but as valuable additions as possible (in one case, I just implemented a minimal flux with event emitter just to avoid picking sides on flux frameworks).

So I guess, if that helps, that's the kind of thought process that was put there, the code is merely an expression of that.

Going forward, there are a few challenges, like are these templates spot on, in the sense I just described, how would you detect / solve breakage with minimal maintenance and so on.

**Comment by knowbody** [comment]
I'm not up for taking the "awesome-react-native" under the organisation. As under the organisation we want to have modules people can use. I much rather cherry pick well maintained and documented projects from that list and contact maintainers if they are up for moving their projects.

**Comment by jondot** [comment]
Closing this for now, feel free to reopen if needed
