### ISSUE TITLE
Adding awesome-react-native-talks as sub list

### ISSUE THREAD

**Issue by mightyCrow** [jondot/awesome-react-native#304]
Would you consider adding [awesome-react-native-talks
](https://github.com/mightyCrow/awesome-react-native-talks) as a sub list under the videos section? If so I would like to divide the section into tutorials/training and conference talks.

**Comment by jondot** [comment]
Sure, that would be perfect!

**Comment by mightyCrow** [comment]
@jondot awsome! Will start working on the PR later.
