### ISSUE TITLE
Any License?

### ISSUE THREAD

**Issue by HyperSimon** [jondot/awesome-react-native#413]
I didn't see that in this repo

**Comment by gergob** [comment]
This is a collection of links...why would you need any license definition ?

**Comment by HyperSimon** [comment]
But you pay the time and energy, these are your labor results

**Comment by jondot** [comment]
It's really just a bunch of links, and we had this discussion in the past - there wasn't a complete agreement, not over engineer this unless really everyone thinks the same. If it's really bothers you than  its completely fine if you don't submit a PR, eventually the library will get added by myself or someone else that built it.
