### ISSUE TITLE
Open source app built in React native

### ISSUE THREAD

**Issue by bluedaniel** [jondot/awesome-react-native#43]
I've had my open source app accepted to the app store and would like to add it to your awesome list!

It's an ambient sound mixer and part of a trilogy of apps built with React+Reflux ([web](https://github.com/bluedaniel/Kakapo-web/) / [desktop](https://github.com/bluedaniel/Kakapo-app) / [native](https://github.com/bluedaniel/Kakapo-native))

GitHub: https://github.com/bluedaniel/Kakapo-native
iTunes: https://itunes.apple.com/us/app/kakapo/id1046673139

Thanks!

**Comment by jondot** [comment]
Awesome stuff! 
Adding ! :+1: :+1:

**Comment by bluedaniel** [comment]
Thanks! :smile:
