### ISSUE TITLE
Replace manual stars counting to badges

### ISSUE THREAD

**Issue by szhigunov** [jondot/awesome-react-native#489]
I want to suggest you replace star count ( with star icon ) to well known "star" buttons with counter, like this from https://github.com/sindresorhus/awesome repo: [![GitHub stars](https://img.shields.io/github/stars/bevacqua/awesome-badges.svg?style=social&label=Star)](https://github.com/bevacqua/awesome-badges)

**Comment by jondot** [comment]
Hi,
It was like this initially but it showed to not be optimal. What happens with thousands of links is once you open the page it trashes your internet connection, loads slowly, and at worst kills the page load.
This is why we're keeping the textual numbers.
But thanks for suggesting!

**Comment by szhigunov** [comment]
But who will manage up-to-date README.md ? It's going to outdate every minute. That's main point in this issue.

**Comment by jondot** [comment]
who: currently myself, every now and then - I'm welcoming a better idea :)
what: https://github.com/jondot/jill

**Comment by olivierlesnicki** [comment]
@jondot a CRON job that query the star counts and open a PR?
