### ISSUE TITLE
Attempt to read from field

### ISSUE THREAD

**Issue by huutrancl** [jondot/awesome-react-native#84]
I add a custom search in my project, so I create a listview to show suggestion for search data.
When I change listview's data source, I see "Attempt to read from field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference"
Please help me.

**Comment by ms88privat** [comment]
I got this error if the value of a textfield is undefined

**Comment by jondot** [comment]
I'd like to point out that this may not be the best place to look for troubleshooting advice, it's an "awesome-list".
