### ISSUE TITLE
Error while creating a new react-native application.

### ISSUE THREAD

**Issue by Panda-Srujan** [jondot/awesome-react-native#93]
Hi everyone.

I'm facing the following error while creating a new application in react-native.

`module.js:328 throw err; ^ Error: Cannot find module './modules/es5'`

For your information, I've reinstalled the react-native using the following command.

`npm install -g react-native-cli`

And tried to create a new react-native application using the following command.

`react-native init AwesomeProject`

![react native error while creating new app 2](https://cloud.githubusercontent.com/assets/16679478/12694610/d80b82f6-c758-11e5-9a7a-9812df79bdf8.png)

Please help me out of this.

Thanks in advance.

**Comment by adeshpande3** [comment]
Having the same issue. If anyone knows a possible fix, any help would be much appreciated.

**Comment by dbuarque** [comment]
+1

**Comment by vitalets** [comment]
I think you should ask it in https://github.com/facebook/react-native repo, not here.

**Comment by kevinvangelder** [comment]
This repo is not intended to be a buildable React Native application. Rather, it's simply a consolidated source of information regarding React Native related modules and resources.
